---
Name: Silverstripe GDM Extensions
---
SiteTree:
  extensions:
    - SSGuru_ViewableData
    - SSGuru_SiteTree
ContentController:
  extensions:
    - SSGuru_ContentController
ErrorPage:
  extensions:
    - SSGuru_ErrorPage
ViewableData:
  extensions:
    - SSGuru_ViewableData
Page:
  extensions:
    - SSGuru_PageUtilities
DataObject:
  extensions:
    - SSGuru_ViewableData

