---
Name: Silverstripe GDM Extensions
---
ContentController:
  extensions:
    - SSGuru_ContentController
Controller:
  extensions:
    - SSGuru_Controller
ErrorPage:
  extensions:
    - SSGuru_ErrorPage
Page:
  extensions:
    - SSGuru_PageUtilities
SiteTree:
  extensions:
    - SSGuru_ViewableData
    - SSGuru_SiteTree
ViewableData:
  extensions:
    - SSGuru_ViewableData
GridFieldBulkUpload_Request:
  extensions:
    - SSGuru_KickAssetsGridFieldBulkUpload_Request
Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$CacheRequestFilter'